### ISSUE TITLE
Correctly validate 0.0.2 data block

### ISSUE THREAD

**Issue by necrophonic** [ONSdigital/sdx-validate#17]
Currently returns always valid for `0.0.2` data block. Once format is stable will need updating to more accurately validate.

**Comment by eldeal** [comment]
@necrophonic Is this still an issue?

**Comment by necrophonic** [comment]
Never an "issue" per se, but a possibile enhancement to tighten up validation.

We validate that the block exists and that it is an object (I believe) but not whether the sub structure in that object is correct.

Depends how far you can feasibly go given the variability of the data supplied.
